### ISSUE TITLE
Unknown nodes

### ISSUE THREAD

**Issue by dinmammas** [mkgeiger/node-red-sma#1]
Hello!

I'm trying to use this flow with my HM2.0 but node-red says "unknown: ui_text".
I've yet to find which add on adds these node types. Could you perhaps point me to it?

**Comment by dinmammas** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/27199904/229515471-8d64a27d-eff8-4707-aad6-bab69334d412.png">

**Comment by dinmammas** [comment]
Nvm - sorted it. I was missing node-red-dashboard

**Comment by mkgeiger** [comment]
Thanks for the question. I wanted just to respond with the same. Please install "npm install node-red-dashboard".
