### ISSUE TITLE
Certificate Error while connecting to inverter

### ISSUE THREAD

**Issue by HerrVonundZu** [mkgeiger/node-red-sma#2]
Well done and thank you for the good work. I am using a Smarthome Manager 2.0 and A Sunny Tripower SE 10.0 inverter.
during the config i reconized certifacte errors. So i activated the secure ssl connection and unticked the check Server option. Unfortunatly i dont recieve any usefull information, instead the message "TypeError: Cannot read properties of undefined"
appears.

**Comment by mkgeiger** [comment]
First you need to activate (tick) the Webconnect Server of your Sunny Tripower. This option is only available for the installer (german: Installateur) account of the Sunny Tripower. Did you change anything to the javascript source code of the nodes except of the user and password? Maybe some typo in the javascript source code happend? The message "TypeError: Cannot read properties of undefined" typically comes when you try to access a property of an undefined value (e.g. variable, function, object, etc.), e.g. also if you never assigned a value to a variable before.

**Comment by HerrVonundZu** [comment]
i tried again. and dobluechecked typos etc.  The webconnect server version is 1.5.4.R and it is activated. Wich password do i have to use? i tried the password of "user"group and also the instraller group password.
the http request  debug is showing this meesage:

msg : Object
object
payload: object
result: object
sid: null
topic: ""
_msgid: "f11ce796f92f5418"
headers: object
content-type: "application/json;"
cache-control: "no-store, no-cache, must-revalidate, post-check=0, pre-check=0, max-age=0"
content-length: "23"
connection: "close"
date: "Sun, 21 May 2023 12:14:08 GMT"
server: "lighttpd/1.4.54"
x-node-red-request-node: "fb24c57e"
statusCode: 200
responseUrl: "https://192.168.1.199/dyn/login.json"
redirectList: array[0]
retry: 0

**Comment by mkgeiger** [comment]
Your response message from the 1st HTTP-request-node looks fine, except SID (null) and maybe the content length is too short in your dump, which could indicate some problem with the login user data which is configured in the 1st Change-node. Make sure msg.payload in the 1st Change-node is configured for the User account of the inverter like e.g.: {"right": "usr", "pass": "YOUR_USER_PASSWORD"}

As a reference I debugged my response message of the 1st HTTP-request-node where I get back a valid SID:
{"payload":{"result":{"sid":"_p7isux6yas60uRx"}},"topic":"","_msgid":"b9fef4cd.ae8888","headers":{"content-type":"application/json;","cache-control":"no-store, no-cache, must-revalidate, post-check=0, pre-check=0, max-age=0","content-length":"37","date":"Sun, 21 May 2023 18:12:24 GMT","server":"lighttpd/1.4.54","x-node-red-request-node":"551f0a84"},"statusCode":200,"responseUrl":"https://192.168.1.150/dyn/login.json","redirectList":[]}
