### ISSUE TITLE
For buffer-parser: This node is a type unknown to your installation of Node-RED.

### ISSUE THREAD

**Issue by Denis1983** [mkgeiger/node-red-sma#6]
For buffer-parser: This node is a type unknown to your installation of Node-RED.

![2024-10-13 20_03_59-Node-RED _ ccu3-webui](https://github.com/user-attachments/assets/32f26b20-c841-4560-96f8-4cf9d273f4ee)

**Comment by mkgeiger** [comment]
Please install the buffer parser node first:
npm install node-red-contrib-buffer-parser

**Comment by Denis1983** [comment]
Thank you!
Do you know how to align the values?

![image](https://github.com/user-attachments/assets/1920d6ff-2494-45e5-8916-31ec209c61dd)

**Comment by mkgeiger** [comment]
Open Node-Red editor (https://your_ip:1880).  Then select "Dashboard" button on the right side of right window. In "Layout" tab select the layout you want to modify/edit. A layout editor opens and you can delete, add, move, re-arrange the graphical elements.
![grafik](https://github.com/user-attachments/assets/019512b3-9562-4880-8d35-35fd2944be29)
